common: &common
  adapter: mysql2
  database_timezone: local
  pool: 100
  password: Dcsd195617
  connect_timeout: 20
  timeout: 900
  socket: 
  port: 3306
  username: root
  password: Dcsd195617
development:
  <<: *common
  adapter: mysql2
  database: code_test
